### ISSUE TITLE
Couple of questions!

### ISSUE THREAD

**Issue by Irbopia** [ringcentral/ringcentral-integration-for-hubspot#12]
We are really saving a ton of time with this integration. So first of all, I'd just like to say thank you!

1. Is this integration designed to sync our sales reps Hubspot contacts into the ring central overlay? We only see our ring central contacts currently. 

2. Any eta or beta for syncing SMS to hubspot?

**Comment by zxdong262** [comment]
@Irbopia 
1. No, it only serves as call provider, same function as HubSpot native call provider
2. I will add this to todo list, may take some time.

Feel free to ask if you have any issues using it.

At the same time, you may want to use our Chrome extension, which provide more features, this is the compare table: https://github.com/ringcentral/ringcentral-integration-for-hubspot/blob/master/features-compare.md

**Comment by Irbopia** [comment]
I've tried walking through all of the steps in your support documentation and our SMS messages with the chrome extension are not syncing as notes still. Would it be helpful if I sent you screen recordings with any bugs we are running into?

**Comment by zxdong262** [comment]
@Irbopia Chrome extension is different app, not related to the integration in app market, do check the video https://youtu.be/ajbipkPd_4Q and remember to turn on auto log in settings.
