### ISSUE TITLE
SMS Log not working

### ISSUE THREAD

**Issue by macodeta** [ringcentral/ringcentral-integration-for-hubspot#16]
The SMS log is not clickable. It is also not functioning for the sync. Our calls are ok but SMS are not synced or logged.
![Not clickable](https://user-images.githubusercontent.com/64639118/109615236-a5032d80-7b6e-11eb-8413-6e991da04d89.jpg)

**Comment by zxdong262** [comment]
Fixed in latest release, thank you for the feedback
