### ISSUE TITLE
Need the ability to take notes during the call.

### ISSUE THREAD

**Issue by wss-chadical** [ringcentral/ringcentral-integration-for-hubspot#2]
Pretty nice integration - soooo close.

We could use this if the Call Notes were available during the call...

**Comment by wss-chadical** [comment]
It looks like the sdk supports having hubspot create the engagement before the call... and can provide the engagement id.

**Comment by zxdong262** [comment]
Updated, now you can log the call when calling

**Comment by wss-chadical** [comment]
That's some progress.

Ideally, users should not have to click a button to log the call on the timeline.

If a call is made out - a call engagement is always created.
If a note is entered in the call window - that goes along with the engagement.

Also, the page needs to be refreshed to see the actual call engagement on the timeline.
There is no good way to log the Call Outcome, etc...

I know Hubspot's SDK's can be lacking.

**Comment by wss-chadical** [comment]
Ideally - the call process should mirror as closely as possible the native call experience in hubspot.

**Comment by zxdong262** [comment]
@wss-chadical Thank you for the advice, yes, the call log part is not part of calling SDK, so may not be able to update web UI as the native one, other things, I can improve.

**Comment by zxdong262** [comment]
@wss-chadical Now for the same call, multi logs goes to the same log entry.

**Comment by TrumpiaTim** [comment]
So when we make a call, it does not AUTO LOG? 

This seems to conflict with the key benefit listed here: https://app.hubspot.com/ecosystem/2803674/marketplace/apps/sales/calling/ringcentral-202602

**"Calls can be made using RingCentral from directly in HubSpot. After each call, the call will be automatically synced to the HubSpot call log for tracking."**

**Comment by zxdong262** [comment]
@TrumpiaTim You are right, should auto log when user did not log the call.

**Comment by zxdong262** [comment]
@TrumpiaTim Updated, now note will only sync with call log when call ends automatically. Thank you for the feedback.

@wss-chadical

**Comment by TrumpiaTim** [comment]
Great, so call log is automatically recorded but when I send out a text message that's not automatically recording to the hubspot contact.

**Comment by TrumpiaTim** [comment]
Also for the automatically call logging, can you confirm:

Under calling setting, **Make My Calls With** 

Do all 4 auto-log the call into Hubspot? Currently I am experiencing success with the Browser option but when selling the following:
- Ringcentral for Desktop
- Custom Phone
- My RingCentral Phone

None of those 3 are recording to Hubspot despite having success making the call connection.

**Comment by zxdong262** [comment]
@TrumpiaTim SMS log not supported yet, and calling with other device not supported yet, if you want these features, you can try our browser extension: https://www.ringcentral.com/apps/hubspot

**Comment by zxdong262** [comment]
Feel free to submit another issue.
