### ISSUE TITLE
RingCentral Hubspot Integration with Safari on Mac

### ISSUE THREAD

**Issue by brig66** [ringcentral/ringcentral-integration-for-hubspot#3]
I've installed the integration, however, when trying to use it in Safari, I get an error. 

{"message": "Internal server error"}

Can anyone help?

**Comment by zxdong262** [comment]
Still working on it, you can use our browser extension instead: https://www.ringcentral.com/apps/hubspot

**Comment by brig66** [comment]
That shows for Chrome and Firefox, not Safari. Is there a Safari extension? What is the ETA on fixing the core problem?

**Comment by zxdong262** [comment]
@brig66 No Safari support, I can git it fixed this week if everything goes well.

**Comment by brig66** [comment]
Awesome! Thank you!

**Comment by zxdong262** [comment]
@brig66 Done, Can you try it?

**Comment by brig66** [comment]
I don't get an error message, but the RingCentral pop up opens up and then nothing happens. Do i need to reinstall the integration?

**Comment by zxdong262** [comment]
Yes, please try reinstall

**Comment by brig66** [comment]
OK, I will do that. How do I reinstall?

**Comment by zxdong262** [comment]
https://ringcentral.github.io/apps/hubspot

Visit this and click install

**Comment by brig66** [comment]
Now it gives me a 404 error in the pop up

**Comment by zxdong262** [comment]
Can we have a meeting to check it? If you can, please send a email to drake.zhao@ringcentral.com

**Comment by zxdong262** [comment]
If anyone have same problem, please reconnect RingCentral from https://ringcentral.github.io/apps/hubspot, then try select HubSpot as call provider and reselect RingCentral as call provider

**Comment by zxdong262** [comment]
Seems still have problem with Safari, may check it next week.

**Comment by zxdong262** [comment]
For Safari 13+ user, must disable Prevent cross-site tracking in Prefrence->Privacy
