### ISSUE TITLE
Error loading call window.

### ISSUE THREAD

**Issue by ndwilliams3** [ringcentral/ringcentral-integration-for-hubspot#5]
Getting this message when trying to initiate call. The phone widget shows. 

"qz0upjt4k5.execute-api.us-east-1.amazonaws.com’s server IP address could not be found."
OR 
"We're sorry. There was an issue loading the call window Please refresh the page to try again."

<img width="318" alt="Screen Shot 2020-06-19 at 11 59 23 AM" src="https://user-images.githubusercontent.com/1020854/85160836-851c1b80-b224-11ea-9eb4-55853d1b898a.png">

<img width="306" alt="Screen Shot 2020-06-19 at 11 59 03 AM" src="https://user-images.githubusercontent.com/1020854/85160841-864d4880-b224-11ea-9236-6c5d4711d5dd.png">

**Comment by zxdong262** [comment]
Try select HubSpot as call provider and reselect RingCentral as call provider.

**Comment by ndwilliams3** [comment]
that worked
